ignore:
  - "tests/**/*"
  - "other/**/*"

github_checks:
  annotations: true

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
  after_n_builds: 2

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
      - type: patch
        target: auto
  individual_components:
    - component_id: core
      name: Core
      paths:
        - "src/GameFinder.Common/**"
        - "src/GameFinder.RegistryUtils/**"
    - component_id: wine
      name: Wine
      paths:
        - "src/GameFinder.Wine/**"
    - component_id: store_handler_ea_desktop
      name: EA Desktop
      paths:
        - "src/GameCollector.StoreHandlers.EADesktop/**"
    - component_id: store_handler_egs
      name: EGS
      paths:
        - "src/GameCollector.StoreHandlers.EGS/**"
    - component_id: store_handler_gog
      name: GOG
      paths:
        - "src/GameCollector.StoreHandlers.GOG/**"
    - component_id: store_handler_origin
      name: Origin
      paths:
        - "src/GameCollector.StoreHandlers.Origin/**"
    - component_id: store_handler_steam
      name: Steam
      paths:
        - "src/GameCollector.StoreHandlers.Steam/**"
