name: Validate codecov.yml

on:
  push:
    paths:
      - "codecov.yml"
      - ".github/workflows/validate-codecov.yml"
    branches: [ main ]
  pull_request:
    paths:
      - "codecov.yml"
      - ".github/workflows/validate-codecov.yml"
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate
        shell: bash
        run: |
          curl --fail --data-binary @codecov.yml https://codecov.io/validate
